/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "GPIO_Driver.h"
#include "STM.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void delay(void){
	for(volatile uint32_t i = 0; i<500000; i++);
}

int main(void)
{
	GPIO_Handle_t LED[4];

	for	(int i = 0; i < 4; i++){
		LED[i].pGPIOx = (GPIO_RegDef_t *)GPIOD_BASEADDR;
		LED[i].GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15 - i;
		LED[i].GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
		GPIO_Init(&LED[i]);
	}

	for(int i = 0; i < 4; i++){
		GPIO_WriteToOutputPin(&LED[i], DISABLE);
	}
	// GPIO_WriteToOutputPort((GPIO_RegDef_t *)GPIOD_BASEADDR, 0xFF);
	for(;;){
		for (int i = 0; i < 4; i++){

			GPIO_WriteToOutputPin(&LED[i], ENABLE);
			delay();
			GPIO_WriteToOutputPin(&LED[i], DISABLE);

		}
	}

}
