/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "GPIO_Driver.h"
#include "STM.h"
#include "main.h"
uint8_t state = 2;
uint8_t stopDelay = 0;

void EXTI3_IRQHandler(void){
	GPIO_IRQHandling(GPIO_PIN_NO_3);
	state = 0;
	stopDelay = 1;
}

int main(void)
{
	GPIO_Handle_t btn;
	//Button-Konfiguration
	btn.pGPIOx = GPIOD;
	btn.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_3;
	btn.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_FT;

	GPIO_Init(&btn);
	GPIO_IRQInterruptConfig(IRQ_NO_EXTI3,ENABLE);

	//Lauflicht
	/*GPIO_Handle_t LED_Lauflicht[4];
	lauflichtInit(LED_Lauflicht);
	for(int i=0; i<2; i++)
		lauflicht(LED_Lauflicht);
*/
	//Ampelsteuerung
	GPIO_Handle_t ampelLED[3];

	ampelInit(&ampelLED);

	for(;;){
		switch(state){
			case 0: setAmple(ENABLE,DISABLE,DISABLE,ampelLED); delay(2); state =1; break;

			case 1: setAmple(ENABLE,DISABLE,DISABLE,ampelLED); state =2; break;

			case 2: setAmple(ENABLE,ENABLE,DISABLE,ampelLED); state =3; break;

			case 3: setAmple(DISABLE,DISABLE,ENABLE,ampelLED); state =4; break;

			case 4: setAmple(DISABLE,ENABLE,DISABLE,ampelLED); state =1; break;
		}
	}


}

void setAmple(int rot, int gelb, int gruen, GPIO_Handle_t* ampelLED){
	GPIO_WriteToOutputPin(&ampelLED[0], rot);
	GPIO_WriteToOutputPin(&ampelLED[1], gelb);
	GPIO_WriteToOutputPin(&ampelLED[2], gruen);
	delay(5);
}
void lauflicht(GPIO_Handle_t * LED){
	// GPIO_WriteToOutputPort((GPIO_RegDef_t *)GPIOD_BASEADDR, 0xFF);
	for (int i = 0; i < 4; i++){
		GPIO_WriteToOutputPin(&LED[i], ENABLE);
		delay(3);
		GPIO_WriteToOutputPin(&LED[i], DISABLE);

	}
}
void ampelInit(GPIO_Handle_t* ampelLED){
	for	(int i = 0; i < 3; i++){
		ampelLED[i].pGPIOx = GPIOD;
		ampelLED[i].GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
		ampelLED[i].GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
		ampelLED[i].GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
		ampelLED[i].GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
		ampelLED[i].GPIO_PinConfig.GPIO_PinNumber = i;
		GPIO_Init(&ampelLED[i]);
	}
}

void lauflichtInit(GPIO_Handle_t * LED){
	for	(int i = 0; i < 4; i++){
		LED[i].pGPIOx = GPIOD;
		LED[i].GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15 - i;
		LED[i].GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
		LED[i].GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
		LED[i].GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
		LED[i].GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
		GPIO_Init(&LED[i]);
	}

	for(int i = 0; i < 4; i++){
		GPIO_WriteToOutputPin(&LED[i], DISABLE);
	}
}

//Zeit in Sekunden
void delay(int time){
	for(volatile uint32_t i = 0; i<500000*time; i++){
		if(stopDelay == 1){
			stopDelay = 0;
			break;
		}
	}
}
